// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package queries

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
	"github.com/google/uuid"
)

type ConfigClass string

const (
	ConfigClassCompute     ConfigClass = "compute"
	ConfigClassStorage     ConfigClass = "storage"
	ConfigClassIntegration ConfigClass = "integration"
)

type ConfigStatus string

const (
	ConfigStatusPending ConfigStatus = "pending"
	ConfigStatusRunning ConfigStatus = "running"
	ConfigStatusFailed  ConfigStatus = "failed"
	ConfigStatusDeleted ConfigStatus = "deleted"
)

// GetConfigsConfigsPagedConfigsOutput includes the requested fields of the GraphQL type PagedConfigsOutput.
type GetConfigsConfigsPagedConfigsOutput struct {
	Items       []GetConfigsConfigsPagedConfigsOutputItemsConfig `json:"items"`
	Limit       int                                              `json:"limit"`
	Page        int                                              `json:"page"`
	Total_items int                                              `json:"total_items"`
	Total_pages int                                              `json:"total_pages"`
}

// GetItems returns GetConfigsConfigsPagedConfigsOutput.Items, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutput) GetItems() []GetConfigsConfigsPagedConfigsOutputItemsConfig {
	return v.Items
}

// GetLimit returns GetConfigsConfigsPagedConfigsOutput.Limit, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutput) GetLimit() int { return v.Limit }

// GetPage returns GetConfigsConfigsPagedConfigsOutput.Page, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutput) GetPage() int { return v.Page }

// GetTotal_items returns GetConfigsConfigsPagedConfigsOutput.Total_items, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutput) GetTotal_items() int { return v.Total_items }

// GetTotal_pages returns GetConfigsConfigsPagedConfigsOutput.Total_pages, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutput) GetTotal_pages() int { return v.Total_pages }

// GetConfigsConfigsPagedConfigsOutputItemsConfig includes the requested fields of the GraphQL type Config.
type GetConfigsConfigsPagedConfigsOutputItemsConfig struct {
	Id               uuid.UUID                                                         `json:"id"`
	Code             string                                                            `json:"code"`
	Class            ConfigClass                                                       `json:"class"`
	Name             string                                                            `json:"name"`
	Business_unit_id uuid.UUID                                                         `json:"business_unit_id"`
	Folder_id        uuid.UUID                                                         `json:"folder_id"`
	Resources        []GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource `json:"resources"`
	Version_number   string                                                            `json:"version_number"`
	Status           ConfigStatus                                                      `json:"status"`
	Created_at       time.Time                                                         `json:"created_at"`
	Updated_at       time.Time                                                         `json:"updated_at"`
}

// GetId returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Id, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetId() uuid.UUID { return v.Id }

// GetCode returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Code, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetCode() string { return v.Code }

// GetClass returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Class, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetClass() ConfigClass { return v.Class }

// GetName returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Name, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetName() string { return v.Name }

// GetBusiness_unit_id returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Business_unit_id, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetBusiness_unit_id() uuid.UUID {
	return v.Business_unit_id
}

// GetFolder_id returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Folder_id, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetFolder_id() uuid.UUID { return v.Folder_id }

// GetResources returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Resources, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetResources() []GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource {
	return v.Resources
}

// GetVersion_number returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Version_number, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetVersion_number() string {
	return v.Version_number
}

// GetStatus returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Status, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetStatus() ConfigStatus { return v.Status }

// GetCreated_at returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Created_at, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetCreated_at() time.Time {
	return v.Created_at
}

// GetUpdated_at returns GetConfigsConfigsPagedConfigsOutputItemsConfig.Updated_at, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfig) GetUpdated_at() time.Time {
	return v.Updated_at
}

// GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource includes the requested fields of the GraphQL type Resource.
type GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource struct {
	Code         string                 `json:"code"`
	Type         ResourceType           `json:"type"`
	Data         map[string]interface{} `json:"data"`
	References   []string               `json:"references"`
	Allow_access []string               `json:"allow_access"`
}

// GetCode returns GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource.Code, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource) GetCode() string {
	return v.Code
}

// GetType returns GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource.Type, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource) GetType() ResourceType {
	return v.Type
}

// GetData returns GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource.Data, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource) GetData() map[string]interface{} {
	return v.Data
}

// GetReferences returns GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource.References, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource) GetReferences() []string {
	return v.References
}

// GetAllow_access returns GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource.Allow_access, and is useful for accessing the field via an interface.
func (v *GetConfigsConfigsPagedConfigsOutputItemsConfigResourcesResource) GetAllow_access() []string {
	return v.Allow_access
}

// GetConfigsResponse is returned by GetConfigs on success.
type GetConfigsResponse struct {
	Configs GetConfigsConfigsPagedConfigsOutput `json:"configs"`
}

// GetConfigs returns GetConfigsResponse.Configs, and is useful for accessing the field via an interface.
func (v *GetConfigsResponse) GetConfigs() GetConfigsConfigsPagedConfigsOutput { return v.Configs }

// GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput includes the requested fields of the GraphQL type PagedOrganisationsOutput.
type GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput struct {
	Items       []Organisation `json:"items"`
	Limit       int            `json:"limit"`
	Page        int            `json:"page"`
	Total_items int            `json:"total_items"`
	Total_pages int            `json:"total_pages"`
}

// GetItems returns GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput.Items, and is useful for accessing the field via an interface.
func (v *GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput) GetItems() []Organisation {
	return v.Items
}

// GetLimit returns GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput.Limit, and is useful for accessing the field via an interface.
func (v *GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput) GetLimit() int {
	return v.Limit
}

// GetPage returns GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput.Page, and is useful for accessing the field via an interface.
func (v *GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput) GetPage() int {
	return v.Page
}

// GetTotal_items returns GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput.Total_items, and is useful for accessing the field via an interface.
func (v *GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput) GetTotal_items() int {
	return v.Total_items
}

// GetTotal_pages returns GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput.Total_pages, and is useful for accessing the field via an interface.
func (v *GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput) GetTotal_pages() int {
	return v.Total_pages
}

// GetMemberOrganisationsResponse is returned by GetMemberOrganisations on success.
type GetMemberOrganisationsResponse struct {
	MemberOrganisations GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput `json:"memberOrganisations"`
}

// GetMemberOrganisations returns GetMemberOrganisationsResponse.MemberOrganisations, and is useful for accessing the field via an interface.
func (v *GetMemberOrganisationsResponse) GetMemberOrganisations() GetMemberOrganisationsMemberOrganisationsPagedOrganisationsOutput {
	return v.MemberOrganisations
}

// Organisation includes the requested fields of the GraphQL type Organisation.
type Organisation struct {
	Id                 uuid.UUID         `json:"id"`
	Code               string            `json:"code"`
	Name               string            `json:"name"`
	State              OrganisationState `json:"state"`
	Stripe_customer_id string            `json:"stripe_customer_id"`
	Created_at         time.Time         `json:"created_at"`
	Updated_at         time.Time         `json:"updated_at"`
	Deleted_at         time.Time         `json:"deleted_at"`
}

// GetId returns Organisation.Id, and is useful for accessing the field via an interface.
func (v *Organisation) GetId() uuid.UUID { return v.Id }

// GetCode returns Organisation.Code, and is useful for accessing the field via an interface.
func (v *Organisation) GetCode() string { return v.Code }

// GetName returns Organisation.Name, and is useful for accessing the field via an interface.
func (v *Organisation) GetName() string { return v.Name }

// GetState returns Organisation.State, and is useful for accessing the field via an interface.
func (v *Organisation) GetState() OrganisationState { return v.State }

// GetStripe_customer_id returns Organisation.Stripe_customer_id, and is useful for accessing the field via an interface.
func (v *Organisation) GetStripe_customer_id() string { return v.Stripe_customer_id }

// GetCreated_at returns Organisation.Created_at, and is useful for accessing the field via an interface.
func (v *Organisation) GetCreated_at() time.Time { return v.Created_at }

// GetUpdated_at returns Organisation.Updated_at, and is useful for accessing the field via an interface.
func (v *Organisation) GetUpdated_at() time.Time { return v.Updated_at }

// GetDeleted_at returns Organisation.Deleted_at, and is useful for accessing the field via an interface.
func (v *Organisation) GetDeleted_at() time.Time { return v.Deleted_at }

type OrganisationState string

const (
	OrganisationStateNew     OrganisationState = "new"
	OrganisationStateCreated OrganisationState = "created"
	OrganisationStateDeleted OrganisationState = "deleted"
)

type ResourceType string

const (
	ResourceTypeContainer ResourceType = "container"
	ResourceTypeDatabase  ResourceType = "database"
	ResourceTypeBucket    ResourceType = "bucket"
	ResourceTypeQueue     ResourceType = "queue"
)

// __GetConfigsInput is used internally by genqlient
type __GetConfigsInput struct {
	OrganisationId uuid.UUID `json:"organisationId"`
	Page           int       `json:"page"`
	PageSize       int       `json:"pageSize"`
}

// GetOrganisationId returns __GetConfigsInput.OrganisationId, and is useful for accessing the field via an interface.
func (v *__GetConfigsInput) GetOrganisationId() uuid.UUID { return v.OrganisationId }

// GetPage returns __GetConfigsInput.Page, and is useful for accessing the field via an interface.
func (v *__GetConfigsInput) GetPage() int { return v.Page }

// GetPageSize returns __GetConfigsInput.PageSize, and is useful for accessing the field via an interface.
func (v *__GetConfigsInput) GetPageSize() int { return v.PageSize }

// __GetMemberOrganisationsInput is used internally by genqlient
type __GetMemberOrganisationsInput struct {
	UserId   uuid.UUID `json:"userId"`
	Page     int       `json:"page"`
	PageSize int       `json:"pageSize"`
}

// GetUserId returns __GetMemberOrganisationsInput.UserId, and is useful for accessing the field via an interface.
func (v *__GetMemberOrganisationsInput) GetUserId() uuid.UUID { return v.UserId }

// GetPage returns __GetMemberOrganisationsInput.Page, and is useful for accessing the field via an interface.
func (v *__GetMemberOrganisationsInput) GetPage() int { return v.Page }

// GetPageSize returns __GetMemberOrganisationsInput.PageSize, and is useful for accessing the field via an interface.
func (v *__GetMemberOrganisationsInput) GetPageSize() int { return v.PageSize }

// The query or mutation executed by GetConfigs.
const GetConfigs_Operation = `
query GetConfigs ($organisationId: UUID!, $page: Int, $pageSize: Int) {
	configs(input: {organisation_id:$organisationId,page:$page,page_size:$pageSize}) {
		items {
			id
			code
			class
			name
			business_unit_id
			folder_id
			resources {
				code
				type
				data
				references
				allow_access
			}
			version_number
			status
			created_at
			updated_at
		}
		limit
		page
		total_items
		total_pages
	}
}
`

func GetConfigs(
	ctx context.Context,
	client graphql.Client,
	organisationId uuid.UUID,
	page int,
	pageSize int,
) (*GetConfigsResponse, error) {
	req := &graphql.Request{
		OpName: "GetConfigs",
		Query:  GetConfigs_Operation,
		Variables: &__GetConfigsInput{
			OrganisationId: organisationId,
			Page:           page,
			PageSize:       pageSize,
		},
	}
	var err error

	var data GetConfigsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetMemberOrganisations.
const GetMemberOrganisations_Operation = `
query GetMemberOrganisations ($userId: UUID!, $page: Int, $pageSize: Int) {
	memberOrganisations(input: {user_id:$userId,page:$page,page_size:$pageSize}) {
		items {
			id
			code
			name
			state
			stripe_customer_id
			created_at
			updated_at
			deleted_at
		}
		limit
		page
		total_items
		total_pages
	}
}
`

func GetMemberOrganisations(
	ctx context.Context,
	client graphql.Client,
	userId uuid.UUID,
	page int,
	pageSize int,
) (*GetMemberOrganisationsResponse, error) {
	req := &graphql.Request{
		OpName: "GetMemberOrganisations",
		Query:  GetMemberOrganisations_Operation,
		Variables: &__GetMemberOrganisationsInput{
			UserId:   userId,
			Page:     page,
			PageSize: pageSize,
		},
	}
	var err error

	var data GetMemberOrganisationsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
