name: "go: build dev binaries"

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Tag it
        uses: sersoft-gmbh/running-release-tags-action@v2
        with:
          tag: dev